spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

#spring.datasource.name=mg
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3309/woco2?serverTimeZone=UTC
## 3306/excelshiftproblem
##spring.datasource.url=jdbc:mysql://192.168.1.101:3306/traceability?serverTimezone=UTC
#spring.datasource.username=remoteuser
#spring.datasource.password=remote
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.datasource.name=woconew
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=woco;trustServerCertificate=true
spring.datasource.username=remoteuser
spring.datasource.password=remote@321
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update

server.ssl.key-alias=remote
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:sparkMindaHttps.jks
server.ssl.key-store-password=remote
server.port=8095
spring.main.allow-circular-references=true
java.opts=-Xmx20g
server.servlet.context-path=/WebApplication
server.error.whitelabel.enabled=false
zpl.renderer.path=E:/Renderer/ZplRenderer.exe


# used for mail purpose in document approval system
spring.profiles.active=local 

# for server


#SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

#will use this in the WebPageController.java for setting attribute in html 
# app.server.transitionbaseUrl=https://192.168.0.10:8095


# not in use

#app.images.directory=D:/Begapt/excel_sheet/excel_pd_images
#app.images.directory=D:/bega/pd_imagefolder


#zebra.label.template=^XA\n^CI28\n^PW600\n^LL300\n^FO20,20^BQN,2,6^FDLA,%s^FS\n^FO200,20^A0N,30,30^FDPart No.: %s^FS\n^FO200,60^A0N,30,30^FDQuantity: %s pieces^FS\n^FO200,100^A0N,30,30^FDLot Number: %s^FS\n^FO200,140^A0N,30,30^FDIncoming Date: %s^FS\n^FO200,180^A0N,30,30^FDMfg Date: %s^FS\n^FO200,220^A0N,30,30^FDExpiry Date: %s^FS\n^FO20,200^A0N,30,30^FD%s^FS\n^XZ
#zebra.label.template=^XA\
#^CI28\
#^PW480\
#^LL320\
#^FO15,40^BQN,2,4^FDLA,%s^FS\
#^FO120,40^A0N,25,25^FDPart Number.: %s^FS\
#^FO120,70^A0N,25,25^FDQuantity: %s^FS\
#^FO120,100^A0N,25,25^FDLot Number.: %s^FS\
#^FO120,150^A0N,25,25^FDIncoming Date: %s^FS\
#^FO120,180^A0N,25,25^FDMfg Date: %s^FS\
#^FO120,210^A0N,25,25^FDExp Date: %s^FS\
#^FO10,150^A0N,25,25^FD%s^FS\
#^XZ\

supplier.claim.files.path=D:/uploads/supplier_claim/

zebra.label.template=^XA\
^CI28\
^PW480\
^LL360\
^FO15,40^BQN,2,4^FDLA,%s^FS\
^FO120,40^A0N,25,25^FDPart Number.: %s^FS\
^FO120,70^A0N,25,25^FDQuantity: %s^FS\
^FO120,100^A0N,25,25^FDLot Number.: %s^FS\
^FO120,130^A0N,25,25^FDSupplier: %s^FS\
^FO120,160^A0N,25,25^FDBox No.: %s^FS\
^FO120,190^A0N,25,25^FDIncoming Date: %s^FS\
^FO120,220^A0N,25,25^FDMfg Date: %s^FS\
^FO120,250^A0N,25,25^FDExp Date: %s^FS\
^FO120,280^A0N,25,25^FDUser: %s^FS\
^FO10,160^A0N,25,25^FD%s^FS\
^XZ\



#zebra.rack.label.template=^XA\
#^CI28\
#^PW400\
#^LL250\
#^FO40,30^BQN,2,6^FDLA,%s^FS\
#^FO180,80^A0N,35,35^FD%s^FS\
#^XZ

zebra.rack.label.template=^XA\
^PW500\
^LL250\
^FO20,20^BQN,2,4^FDLA,%s^FS\
^FO150,20^A0N,30,30^FD%s - %s^FS\
^FO150,60^A0N,30,30^FD%s - %s^FS\
^FO150,100^A0N,30,30^FD%s - Location Number^FS\
^FO20,180^A0N,35,35^FD%s^FS\
^XZ

printer.default=\\\\10.81.31.29\\iot


# ✅ Network Printer (UNC Path)
printer.iot=\\\\10.81.31.29\\iot

printer.iot.quarantine=ZDesigner ZD230-203dpi ZPL (redirected 2)

# ✅ QA LABEL TEMPLATE


#zebra.qa.label.template=^XA\
#^CI28\
#^PW480\
#^LL320\
#^LH0,0\
#^FO10,40^A0N,28,28^FD%s^FS\
#^FO10,80^A0N,22,22^FDPart No: %s^FS\
#^FO10,105^A0N,22,22^FDQuantity: %s^FS\
#^FO10,130^A0N,22,22^FDSupplier: %s^FS\
#^FO10,155^A0N,22,22^FDBox: %s^FS\
#^FO10,180^A0N,20,20^FDLot: %s^FS\
#^FO10,205^A0N,20,20^FDDT: %s^FS\
#^FO10,230^A0N,20,20^FDUser: %s^FS\
#^FO350,60^BQN,2,4^FDLA,%s^FS\
#^XZ

zebra.qa.label.template=^XA\
^CI28\
^PW480\
^LL320\
^LH0,0\
^FO10,40^A0N,28,28^FD%s^FS\
^FO10,80^A0N,25,25^FDPart No: %s^FS\
^FO10,105^A0N,25,25^FDQuantity: %s^FS\
^FO10,130^A0N,25,25^FDSupplier: %s^FS\
^FO10,155^A0N,25,25^FDBox: %s^FS\
^FO10,180^A0N,25,25^FDLot: %s^FS\
^FO10,205^A0N,25,25^FDDT: %s^FS\
^FO10,230^A0N,25,25^FDUser: %s^FS\
^FO350,60^BQN,2,4^FDLA,%s^FS\
^FO330,170^A0N,18,18^FD%s^FS\
^XZ

qa.upload.path=D:/uploads/qa_docs/
server.address=0.0.0.0