package web.minda.project.controller;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;

import java.util.UUID;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.openxml4j.opc.OPCPackage;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.env.Environment;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletResponse;
import web.minda.project.dto.AutoGeneratedPlanDTO;
import web.minda.project.dto.MouldAvailabilityResponse;
import web.minda.project.dto.PreventiveMaintenanceDTO;
import web.minda.project.dto.ProductionPlanningDTO;
import web.minda.project.entity.LocationMaster;
import web.minda.project.entity.MachineMaster;
import web.minda.project.entity.MouldChildPartMaster;
import web.minda.project.entity.MouldMaster;
import web.minda.project.entity.MouldPreventiveMaintenanceMaster;
import web.minda.project.entity.ProductionArticleCategoryMaster;
import web.minda.project.entity.ProductionArticleMaster;
import web.minda.project.entity.ProductionMouldMaster;
import web.minda.project.entity.ProductionPlanning;
import web.minda.project.entity.ProductionPlanningAutoGenerateMixingMillAndProduction;
import web.minda.project.entity.ProductionPlanningBatchCuttingAuto;
import web.minda.project.entity.ProductionPlanningChangeoverPlan;
import web.minda.project.entity.ProductionPlanningMixingmillAuto;
import web.minda.project.entity.ProductionPlanningProductionAuto;
import web.minda.project.entity.RackMaster;
import web.minda.project.helper.ExcelUploadHelper;
import web.minda.project.repositories.MouldPreventiveMaintenanceMasterRepository;
import web.minda.project.repositories.ProductionArticleCategoryRepository;
import web.minda.project.repositories.ProductionArticleMasterRepository;
import web.minda.project.repositories.ProductionArticleMouldRepository;
import web.minda.project.repositories.ProductionMouldRepository;
import web.minda.project.repositories.ProductionPlanningBatchCuttingAutoRepository;
import web.minda.project.repositories.ProductionPlanningChangeoverPlanRepository;
import web.minda.project.repositories.ProductionPlanningMixingmillAutoRepository;
import web.minda.project.repositories.ProductionPlanningProductionAutoRepository;

import web.minda.project.repositories.ProductionPlanningAutoGenerateMixingMillAndProductionRepository;
import web.minda.project.repositories.ProductionPlanningRepository;
import web.minda.project.repositories.MachineMasterRepository;
import web.minda.project.repositories.MouldChildPartMasterRepository;
import web.minda.project.repositories.MouldMasterRepository;
import web.minda.project.repositories.MouldPreventiveMaintenanceMasterRepository;
import web.minda.project.service.DateTimeService;
import web.minda.project.service.ZebraUsbPrinterService;

@RestController
@RequestMapping("/Controllers")
public class ProductionPlanningController {

	@Autowired
	MouldPreventiveMaintenanceMasterRepository mouldPreventiveMaintenanceMasterRepositoryObject;

	@Autowired
	MouldChildPartMasterRepository mouldChildPartMasterRepositoryObject;

	@Autowired
	ProductionPlanningRepository productionPlanningRepositoryObject;

	@Autowired
	ProductionPlanningChangeoverPlanRepository productionPlanningChangeoverPlanRepositoryObject;

	@Autowired
	MachineMasterRepository machineMasterRepositoryObject;

	@Autowired
	ProductionArticleCategoryRepository productionArticleCategoryRepositoryObject;

	@Autowired
	MouldMasterRepository mouldMasterRepositoryObject;
	
	@Autowired
	ProductionArticleMouldRepository productionArticleMouldRepository;
	
	@Autowired
	ProductionMouldRepository productionMouldRepository ;
	@Autowired
	ProductionArticleMasterRepository productionArticleMasterRepository;
	
	@Autowired
	ProductionPlanningProductionAutoRepository planningProductionAutoRepository;
	
	@Autowired
	ProductionPlanningMixingmillAutoRepository planningMixingmillAutoRepository;
	
	@Autowired
	ProductionPlanningBatchCuttingAutoRepository planningBatchCuttingAutoRepository;
	
	


	@Autowired
	private DateTimeService dateTimeService;

	@Autowired
	private ZebraUsbPrinterService printerService;

	@Value("${qa.upload.path}")
	private String folderPath;

	@Autowired
	private Environment env;

	@Autowired
	ProductionPlanningAutoGenerateMixingMillAndProductionRepository planningAutoGenerateMixingMillAndProductionRepository;
	
	

	
	
	@PostMapping("/insertProductionPlanningChangeOverPlan")
	public ResponseEntity<Object> insertProductionPlanningChangeOverPlan(
	        @RequestBody ProductionPlanningChangeoverPlan jsonObject) {

	    try {

	        System.out.println("===== REQUEST RECEIVED =====");
	        System.out.println("MOULD     : " + jsonObject.getMouldName());
	        System.out.println("MACHINE   : " + jsonObject.getMachineName());
	        System.out.println("ARTICLE   : " + jsonObject.getArticle());
	        System.out.println("PLAN TYPE : " + jsonObject.getPlanType());

	        Optional<ProductionMouldMaster> mouldOptional =
	        		productionMouldRepository.findByMould(jsonObject.getMouldName());

	        System.out.println("MOULD FOUND: " + mouldOptional.isPresent());

	        if (!mouldOptional.isPresent()) {
	            System.out.println("❌ MOULD NOT FOUND IN DB");
	            return new ResponseEntity<>("Mould not found.", HttpStatus.NOT_ACCEPTABLE);
	        }

	        // 🔥 STEP 3 - MACHINE CHECK
	        Optional<MachineMaster> machineOptional =
	                machineMasterRepositoryObject.findByMachineName(jsonObject.getMachineName());

	        System.out.println("MACHINE FOUND: " + machineOptional.isPresent());

	        if (!machineOptional.isPresent()) {
	            System.out.println("❌ MACHINE NOT FOUND IN DB");
	            return new ResponseEntity<>("Machine not found.", HttpStatus.NOT_ACCEPTABLE);
	        }

	        Optional<ProductionArticleMaster> articleOptional =
	        		productionArticleMasterRepository.findByArticle(jsonObject.getArticle());

	        System.out.println("ARTICLE FOUND: " + articleOptional.isPresent());

	        if (!articleOptional.isPresent()) {
	            System.out.println("❌ ARTICLE NOT FOUND IN DB");
	            return new ResponseEntity<>("Article not found.", HttpStatus.NOT_ACCEPTABLE);
	        }

	        Optional<ProductionPlanningChangeoverPlan> productionOptional =
	                productionPlanningChangeoverPlanRepositoryObject
	                        .findTopByMachineNameOrderBySequenceNoDesc(jsonObject.getMachineName());

	        if (productionOptional.isPresent()) {
	            jsonObject.setSequenceNo(productionOptional.get().getSequenceNo() + 1);
	        } else {
	            jsonObject.setSequenceNo(1L);
	        }

	        // 🔥 STEP 6 - FINAL SAVE
	        jsonObject.setStatus("Pending");
	        jsonObject.setPendingShots(0L);
	        jsonObject.setAutoGeneratedSaved(0);
	        jsonObject.setDateTimeCreation(dateTimeService.getCurrentDateAndTime());
	        jsonObject.setDateTimeModified(dateTimeService.getCurrentDateAndTime());

	        productionPlanningChangeoverPlanRepositoryObject.save(jsonObject);

	        System.out.println("✅ SUCCESSFULLY SAVED");

	        return new ResponseEntity<>("Data added successfully.", HttpStatus.OK);

	    } catch (Exception e) {
	        System.out.println("🔥 EXCEPTION OCCURRED");
	        e.printStackTrace();
	        return new ResponseEntity<>("Something went wrong.", HttpStatus.INTERNAL_SERVER_ERROR);
	    }
	}

//	@PostMapping("/takeActionOnPlan")
//	public ResponseEntity<Object> takeActionOnPlan(@RequestBody ProductionPlanningChangeoverPlan jsonObject) {
//		try {
//
//			Optional<ProductionPlanningChangeoverPlan> productionPlanOptional = productionPlanningChangeoverPlanRepositoryObject
//					.findByChangeoverId(jsonObject.getChangeoverId());
//
//			if (productionPlanOptional.isPresent()) {
//
//				ProductionPlanningChangeoverPlan actionTakenObject = productionPlanOptional.get();
//
//				if (jsonObject.getPriority().toLowerCase().equals("high")
//						|| jsonObject.getPriority().toLowerCase().equals("medium")
//						|| jsonObject.getPriority().toLowerCase().equals("low")
//						|| jsonObject.getPriority().toLowerCase().equals("hold")) {
//
//					actionTakenObject.setStatus("Pending");
//					actionTakenObject.setPriority(jsonObject.getPriority());
//					actionTakenObject.setRemark(jsonObject.getRemark());
//					actionTakenObject.setDateTimeModified(dateTimeService.getCurrentDateAndTime());
//
//					productionPlanningChangeoverPlanRepositoryObject.save(actionTakenObject);
//
//				} else if (jsonObject.getPriority().toLowerCase().equals("urgent")) {
//
//					Optional<ProductionPlanning> runningPlanOptional = productionPlanningRepositoryObject
//							.findByMachineName(jsonObject.getMachineName());
//
//					if (!runningPlanOptional.isPresent()) {
//						return new ResponseEntity<>("No plan exist on machine.", HttpStatus.NOT_FOUND);
//					}
//
//					ProductionPlanning runningPlan = runningPlanOptional.get();
//
//					Optional<ProductionPlanningChangeoverPlan> previousProductionPlanOptional = productionPlanningChangeoverPlanRepositoryObject
//							.findByChangeoverId(runningPlan.getChangeoverId());
//
//					if (!previousProductionPlanOptional.isPresent()) {
//
//						actionTakenObject.setStatus("Running");
//						actionTakenObject.setPriority(jsonObject.getPriority());
//						actionTakenObject.setRemark(jsonObject.getRemark());
//						actionTakenObject.setDateTimeModified(dateTimeService.getCurrentDateAndTime());
//
//						productionPlanningChangeoverPlanRepositoryObject.save(actionTakenObject);
//
//						runningPlan.setStatus("Running");
//						runningPlan.setPriority(jsonObject.getPriority());
//						runningPlan.setMachineName(actionTakenObject.getMachineName());
//						runningPlan.setTonnage(actionTakenObject.getTonnage());
//						runningPlan.setMouldName(actionTakenObject.getMouldName());
//						runningPlan.setArticle(actionTakenObject.getArticle());
//						runningPlan.setPlannedShots(actionTakenObject.getPlannedShots());
//						runningPlan.setActualShots(actionTakenObject.getPendingShots());
//						runningPlan.setDateTimeModified(dateTimeService.getCurrentDateAndTime());
//					//	runningPlan.setChangeoverId(actionTakenObject.getChangeoverId());
//
//						productionPlanningRepositoryObject.save(runningPlan);
//
//					} else {
//
//						ProductionPlanningChangeoverPlan previousPlanActionTakenObject = previousProductionPlanOptional
//								.get();
//
//						previousPlanActionTakenObject.setStatus("Pending");
//						previousPlanActionTakenObject.setPriority("High");
//						previousPlanActionTakenObject
//								.setRemark("Due to urgent manufacture article" + actionTakenObject.getArticle());
//						previousPlanActionTakenObject.setPendingShots((runningPlan.getActualShots()));
//						previousPlanActionTakenObject.setDateTimeModified(dateTimeService.getCurrentDateAndTime());
//
//						productionPlanningChangeoverPlanRepositoryObject.save(previousPlanActionTakenObject);
//
//						actionTakenObject.setStatus("Running");
//						actionTakenObject.setPriority(jsonObject.getPriority());
//						actionTakenObject.setRemark(jsonObject.getRemark());
//						actionTakenObject.setDateTimeModified(dateTimeService.getCurrentDateAndTime());
//
//						productionPlanningChangeoverPlanRepositoryObject.save(actionTakenObject);
//
//						runningPlan.setStatus("Running");
//						runningPlan.setPriority(jsonObject.getPriority());
//						runningPlan.setMachineName(actionTakenObject.getMachineName());
//						runningPlan.setTonnage(actionTakenObject.getTonnage());
//						runningPlan.setMouldName(actionTakenObject.getMouldName());
//						runningPlan.setArticle(actionTakenObject.getArticle());
//						runningPlan.setPlannedShots(actionTakenObject.getPlannedShots());
//						runningPlan.setActualShots(actionTakenObject.getPendingShots());
//						runningPlan.setDateTimeModified(dateTimeService.getCurrentDateAndTime());
//						runningPlan.setChangeoverId(actionTakenObject.getChangeoverId());
//
//						productionPlanningRepositoryObject.save(runningPlan);
//
//					}
//
//				} else if (jsonObject.getPriority().toLowerCase().equals("shift plan")) {
//
//					if (actionTakenObject.getStatus().toLowerCase().equals("pending")) {
//
//						actionTakenObject.setStatus("Pending");
//						actionTakenObject.setMachineName(jsonObject.getTonnage());
//						actionTakenObject.setPriority("Low");
//						actionTakenObject.setRemark(jsonObject.getRemark());
//						actionTakenObject.setDateTimeModified(dateTimeService.getCurrentDateAndTime());
//
//						productionPlanningChangeoverPlanRepositoryObject.save(actionTakenObject);
//
//					} else {
//						
//						return new ResponseEntity<>("Running Plan can not be shifted.", HttpStatus.NOT_ACCEPTABLE);
//
//					}
//				}
//
//				return new ResponseEntity<>("Plan updated successfully.", HttpStatus.OK);
//
//			} else {
//				return new ResponseEntity<>("Something went wrong.", HttpStatus.NOT_FOUND);
//			}
//
//		} catch (Exception e) {
//			e.printStackTrace();
//			return new ResponseEntity<>("Something went wrong.", HttpStatus.INTERNAL_SERVER_ERROR);
//		}
//	}

	@PostMapping("/getLikeProductionPlanning/{pageNum}/{pageSize}")
	public ResponseEntity<Object> getLikeProductionPlanning(@PathVariable("pageNum") int page,
			@PathVariable("pageSize") int pageSize, @RequestBody ProductionPlanningChangeoverPlan jsonObject) {

		try {
			Pageable pageable = PageRequest.of(page, pageSize);
			
			System.out.println("Machine: " + jsonObject.getMachineName());
			System.out.println("Article: " + jsonObject.getArticle());
			System.out.println("Priority: " + jsonObject.getPriority());
			System.out.println("Status: " + jsonObject.getStatus());
			System.out.println("PlannedDate: " + jsonObject.getPlannedDate());
			System.out.println("PlannedDate: " + jsonObject.getDateTimeModified());

			String priorityString = jsonObject.getPriority().toLowerCase().equals("all") ? ""
					: jsonObject.getPriority();

			String statusString = jsonObject.getStatus().toLowerCase().equals("all") ? "" : jsonObject.getStatus();
			String machineString = jsonObject.getMachineName().toLowerCase().equals("all") ? "" : jsonObject.getMachineName();

			System.out.println(statusString + priorityString + "Running this line");
			
			Page<ProductionPlanningDTO> object = this.productionPlanningRepositoryObject.getLikeProductionPlanning(
					machineString, jsonObject.getArticle(), statusString, priorityString, jsonObject.getPlannedDate(), pageable);

			return new ResponseEntity<Object>(object, HttpStatus.OK);

		} catch (Exception e) {
			System.out.println(e);
			return new ResponseEntity<Object>("ng", HttpStatus.OK);
		}
	}
	
	

	
	
	@GetMapping("/checkMouldAvailability")
	public ResponseEntity<?> checkMouldAvailability(
	        @RequestParam String mould,
	        @RequestParam String article,
	        @RequestParam String plannedDate,
	        @RequestParam String machineName
	) {

	    Integer minShots = productionPlanningChangeoverPlanRepositoryObject.getMinShotsByMould(mould);
	    if (minShots == null) minShots = 0;

	    Integer usedShots = productionPlanningChangeoverPlanRepositoryObject.getUsedShotsByMouldAndDate(mould, plannedDate);
	    if (usedShots == null) usedShots = 0;

	    int remainingShots = minShots - usedShots;
	    if (remainingShots < 0) remainingShots = 0;

	    // ✅ check mould already running on other machine (including duplicate)
	    String usedInMachine =
	            productionPlanningChangeoverPlanRepositoryObject.findOtherMachineUsingMouldOrDuplicate(
	                    mould, plannedDate, machineName
	            );

	    boolean isAlreadyUsed = usedInMachine != null;

	    MouldAvailabilityResponse response = new MouldAvailabilityResponse(
	            minShots,
	            usedShots,
	            remainingShots,
	            isAlreadyUsed,
	   
	            usedInMachine
	    );

	    return ResponseEntity.ok(response);
	}
	
	
	private String generatePlanId() {

	    return  LocalDateTime.now()
	            .format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"))
	            + "-"
	            + UUID.randomUUID()
	            .toString()
	            .substring(0, 8);

	}
	

	
	@PostMapping("/saveAutoGeneratedPlan")
	public ResponseEntity<?> saveAutoGeneratedPlan(
	        @RequestBody AutoGeneratedPlanDTO dto) {

	    // One Plan ID for complete upload
	    String commonPlanId = generatePlanId();

	    dto.getMachinePlans().forEach(machine -> {

	        savePlanData(
	                machine.getMachineName(),
	                machine.getMainChangeoverId(),
	                commonPlanId,
	                dto
	        );

	        savePlanData(
	                machine.getMachineName(),
	                machine.getNextChangeoverId(),
	                commonPlanId,
	                dto
	        );

	        savePlanData(
	                machine.getMachineName(),
	                machine.getSpareChangeoverId(),
	                commonPlanId,
	                dto
	        );
	    });

	    return ResponseEntity.ok("Saved Successfully");
	}

	private void savePlanData(
	        String machineName,
	        Long changeoverId,
	        String planId,
	        AutoGeneratedPlanDTO dto) {

	    System.out.println("=================================");
	    System.out.println("SAVE METHOD CALLED");

	    System.out.println("Machine: " + machineName);

	    System.out.println("ChangeoverId: " + changeoverId);

	    if (changeoverId == null) {
	        return;
	    }

	    ProductionPlanningChangeoverPlan plan =
	            productionPlanningChangeoverPlanRepositoryObject
	                    .findById(changeoverId)
	                    .orElseThrow(() ->
	                            new RuntimeException(
	                                    "Invalid ChangeoverId: " + changeoverId
	                            ));
	    
	    
	    Optional<ProductionPlanning> existingProduction =
	            productionPlanningRepositoryObject
	            .findByMachineNameAndArticleAndPlannedDate(
	                    plan.getMachineName(),
	                    plan.getArticle(),
	                    dto.getPlannedDate()
	            );


	    if(existingProduction.isPresent()){

	        System.out.println(
	            "Duplicate found : "
	            + plan.getMachineName()
	            + " "
	            + plan.getArticle()
	            + " "
	            + dto.getPlannedDate()
	        );

	        return;
	    }
	    

	 plan.setPlanId(planId);
	 plan.setPlannedDate(
		        dto.getPlannedDate()
		);

	    plan.setAutoGeneratedSaved(1);

	    productionPlanningChangeoverPlanRepositoryObject.save(plan);
	    
	    
	 // ==========================================
	 // COPY CHANGEOVER PLAN TO PRODUCTION PLANNING
	 // ==========================================

	 ProductionPlanning production = new ProductionPlanning();


	 production.setSequenceNo(plan.getSequenceNo());

	 production.setArticle(plan.getArticle());

	 production.setBatchCode(plan.getBatchCode());

	 production.setMouldName(plan.getMouldName());


	 production.setDuplicateMouldName(
	         plan.getDuplicateMouldName()
	 );


	 production.setChildPartName(
	         plan.getChildPartName()
	 );


	 production.setChildPartType(
	         plan.getChildPartType()
	 );


	 production.setPlannedShots(
	         plan.getPlannedShots()
	 );


	 production.setPriority(
	         plan.getPriority()
	 );


	 production.setPlannedDate(
		        dto.getPlannedDate()
		);

	 production.setCreatedBy(
	         plan.getCreatedBy()
	 );


	 production.setStatus(
	         "Pending"
	 );


	 production.setDateTimeCreation(
	         dateTimeService.getCurrentDateAndTime()
	 );


	 production.setDateTimeModified(
	         dateTimeService.getCurrentDateAndTime()
	 );


	 production.setMachineName(
	         plan.getMachineName()
	 );


	 production.setTonnage(
	         plan.getTonnage()
	 );


	 production.setRemark(
	         plan.getRemark()
	 );


	 production.setImage(
	         plan.getImage()
	 );


	 production.setPendingShots(
	         plan.getPendingShots()
	 );


	 production.setPlanType(
	         plan.getPlanType()
	 );


	 production.setAutoGeneratedSaved(
	         plan.getAutoGeneratedSaved()
	 );


	 production.setPlanId(
		        plan.getPlanId()
		);

	

	 production.setActualShots(0L);

	
             productionPlanningRepositoryObject.save(production);
     


	}
	
	
	@PostMapping("/sendAutoGeneratedProduction")
	public ResponseEntity<?> sendAutoGeneratedProduction(
	        @RequestBody AutoGeneratedPlanDTO dto){


	    dto.getMixingmillList()
	    .forEach(row -> {


	        Optional<ProductionPlanning> mainPlan =
	                productionPlanningRepositoryObject
	                .findByPlanIdAndMachineNameAndPlanType(
	                        row.getPlanId(),
	                        row.getMachineName(),
	                        "main"
	                );


	        if(mainPlan.isEmpty()){
	            throw new RuntimeException(
	                "Main plan not found for "+row.getPlanId()
	            );
	        }


	        ProductionPlanning plan = mainPlan.get();



	        // ==========================
	        // AUTO ENTRY SHIFT WISE
	        // ==========================

	        if("AUTO".equalsIgnoreCase(row.getEntryType())){


	            List<String> shifts = Arrays.asList(
	                    "A",
	                    "B",
	                    "C"
	            );


	            shifts.forEach(shift -> {


	                ProductionPlanningAutoGenerateMixingMillAndProduction obj =
	                        new ProductionPlanningAutoGenerateMixingMillAndProduction();



	                obj.setPlanId(
	                        plan.getPlanId()
	                );


	                obj.setPlannedDate(
	                        plan.getPlannedDate()
	                );


	                obj.setChangeoverId(
	                        plan.getProductionPlanningId()
	                );


	                obj.setMachineName(
	                        row.getMachineName()
	                );


	                obj.setArticle(
	                        row.getArticle()
	                );


	                obj.setMouldName(
	                        row.getMouldName()
	                );


	                obj.setCompoundCode(
	                        row.getCompoundCode()
	                );


	                obj.setBatchWeight(
	                        row.getBatchWeight()
	                );


	                obj.setShotPerDay(
	                        row.getShotsPerDay()
	                );


	                obj.setPerShotWeight(
	                        row.getPerShotWeight()
	                );


	                obj.setTotalWeight(
	                        row.getTotalWeight()
	                );


	                obj.setSuggestiveBatch(
	                        row.getSuggestiveBatch()
	                );


	                obj.setActualBatch(
	                        row.getActualBatch()
	                );


	                obj.setType(
	                        row.getType()
	                );


	                obj.setEntryType(
	                        "AUTO"
	                );


	                // SHIFT SET HERE
	                obj.setShift(shift);



	                Optional<ProductionPlanningAutoGenerateMixingMillAndProduction> existing =
	                        planningAutoGenerateMixingMillAndProductionRepository
	                        .findByPlanIdAndChangeoverIdAndCompoundCodeAndMouldNameAndTypeAndShift(
	                                obj.getPlanId(),
	                                obj.getChangeoverId(),
	                                obj.getCompoundCode(),
	                                obj.getMouldName(),
	                                obj.getType(),
	                                obj.getShift()
	                        );


	                if(existing.isEmpty()){

	                    obj.setDateTimeModified(
	                        dateTimeService.getCurrentDateAndTime()
	                    );


	                    planningAutoGenerateMixingMillAndProductionRepository
	                    .save(obj);

	                }


	            });


	        }



	        // ==========================
	        // MANUAL ENTRY
	        // ==========================

	        else{


	            ProductionPlanningAutoGenerateMixingMillAndProduction obj =
	                    new ProductionPlanningAutoGenerateMixingMillAndProduction();



	            obj.setPlanId(
	                    plan.getPlanId()
	            );


	            obj.setPlannedDate(
	                    plan.getPlannedDate()
	            );


	            obj.setChangeoverId(
	                    plan.getProductionPlanningId()
	            );


	            obj.setMachineName(
	                    row.getMachineName()
	            );


	            obj.setArticle(
	                    row.getArticle()
	            );


	            obj.setMouldName(
	                    row.getMouldName()
	            );


	            obj.setCompoundCode(
	                    row.getCompoundCode()
	            );


	            obj.setBatchWeight(
	                    row.getBatchWeight()
	            );


	            obj.setShotPerDay(
	                    row.getShotsPerDay()
	            );


	            obj.setPerShotWeight(
	                    row.getPerShotWeight()
	            );


	            obj.setTotalWeight(
	                    row.getTotalWeight()
	            );


	            obj.setSuggestiveBatch(
	                    row.getSuggestiveBatch()
	            );


	            obj.setActualBatch(
	                    row.getActualBatch()
	            );


	            obj.setType(
	                    row.getType()
	            );


	            obj.setEntryType(
	                    "MANUAL"
	            );


	            // MANUAL SHIFT FROM UI
	            obj.setShift(
	                    row.getShift()
	            );


	            obj.setDateTimeModified(
	                    dateTimeService.getCurrentDateAndTime()
	            );


	            // NO DUPLICATE CHECK

	            planningAutoGenerateMixingMillAndProductionRepository
	            .save(obj);

	        }


	    });



	    return ResponseEntity.ok(
	            "Saved Successfully"
	    );

	}
	
	
//	@PostMapping("/sendAutoGeneratedProduction")
//	public ResponseEntity<?> sendAutoGeneratedProduction(
//	        @RequestBody AutoGeneratedPlanDTO dto){
//
//
//	    dto.getMixingmillList()
//	    .forEach(row->{
//	    	
//	    	System.out.println("row: "+ row.getPlanId());
//
//
//	        // fetch MAIN changeover only
//	    	Optional<ProductionPlanning> mainPlan =
//	    	        productionPlanningRepositoryObject
//	    	        .findByPlanIdAndMachineNameAndPlanType(
//	    	                row.getPlanId(),
//	    	                row.getMachineName(),
//	    	                "main"
//	    	        );
//
//
//	        if(mainPlan.isEmpty()){
//	            throw new RuntimeException(
//	                "Main plan not found for "+row.getPlanId()
//	            );
//	        }
//
//
//	        ProductionPlanning plan =
//	                mainPlan.get();
//
//
//
//	        ProductionPlanningAutoGenerateMixingMillAndProduction obj =
//	                new ProductionPlanningAutoGenerateMixingMillAndProduction();
//
//
//
//	        // from main plan
//	        obj.setPlanId(
//	                plan.getPlanId()
//	        );
//
//
//	        obj.setPlannedDate(
//	                plan.getPlannedDate()
//	        );
//
//
//	        obj.setChangeoverId(
//	                plan.getProductionPlanningId()
//	        );
//
//
//
//	        // row data
//
//	        obj.setMachineName(
//	                row.getMachineName()
//	        );
//
//
//	        obj.setArticle(
//	                row.getArticle()
//	        );
//
//
//	        obj.setMouldName(
//	                row.getMouldName()
//	        );
//
//
//	        obj.setCompoundCode(
//	                row.getCompoundCode()
//	        );
//
//
//	        obj.setBatchWeight(
//	                row.getBatchWeight()
//	        );
//
//
//	        obj.setShotPerDay(
//	                row.getShotsPerDay()
//	        );
//
//
//	        obj.setPerShotWeight(
//	                row.getPerShotWeight()
//	        );
//
//
//	        obj.setTotalWeight(
//	                row.getTotalWeight()
//	        );
//
//
//	        obj.setSuggestiveBatch(
//	                row.getSuggestiveBatch()
//	        );
//
//
//	        obj.setActualBatch(
//	                row.getActualBatch()
//	        );
//
//
//	        obj.setType(
//	                row.getType()
//	        );
//	        
//	        obj.setEntryType(
//	        	    row.getEntryType()
//	        	);
//
//
//	        obj.setDateTimeModified(
//	                dateTimeService.getCurrentDateAndTime()
//	        );
//
//	        
////	        Optional<ProductionPlanningAutoGenerateMixingMillAndProduction> existing =
////	                planningAutoGenerateMixingMillAndProductionRepository
////	                .findByPlanIdAndChangeoverIdAndCompoundCodeAndType(
////	                        obj.getPlanId(),
////	                        obj.getChangeoverId(),
////	                        obj.getCompoundCode(),
////	                        obj.getType()
////	                );
//	        
//	        
//	        Optional<ProductionPlanningAutoGenerateMixingMillAndProduction> existing =
//	                planningAutoGenerateMixingMillAndProductionRepository
//	                .findByPlanIdAndChangeoverIdAndCompoundCodeAndMouldNameAndType(
//	                        obj.getPlanId(),
//	                        obj.getChangeoverId(),
//	                        obj.getCompoundCode(),
//	                        obj.getMouldName(),
//	                        obj.getType()
//	                );
//
//
//	        if(existing.isPresent()){
//
//	            System.out.println(
//	                "Duplicate found : "
//	                + obj.getPlanId()
//	                + " "
//	                + obj.getCompoundCode()
//	            );
//
//	            return;
//	        }
//
//
//
//	        planningAutoGenerateMixingMillAndProductionRepository
//	                .save(obj);
//
////
////	        planningAutoGenerateMixingMillAndProductionRepository
////	                .save(obj);
//
//
//	    });
//
//
//
//	    return ResponseEntity.ok(
//	        "Saved Successfully"
//	    );
//	}
	
	
	@DeleteMapping("/deleteAutoGenerate/{id}")
	public ResponseEntity<?> delete(
	        @PathVariable Long id){

	    Optional<ProductionPlanningAutoGenerateMixingMillAndProduction> data =
	            planningAutoGenerateMixingMillAndProductionRepository.findById(id);


	    if(data.isEmpty()){
	        return ResponseEntity.badRequest()
	                .body("Data not found");
	    }


	    ProductionPlanningAutoGenerateMixingMillAndProduction row =
	            data.get();


	    planningAutoGenerateMixingMillAndProductionRepository
	            .deleteByPlanIdAndChangeoverIdAndCompoundCodeAndMouldNameAndType(
	                    row.getPlanId(),
	                    row.getChangeoverId(),
	                    row.getCompoundCode(),
	                    row.getMouldName(),
	                    row.getType()
	            );


	    return ResponseEntity.ok("All Shift Deleted");

	}
	
//	@DeleteMapping("/deleteAutoGenerate/{id}")
//	public ResponseEntity<?> delete(
//	@PathVariable Long id){
//
//		planningAutoGenerateMixingMillAndProductionRepository.deleteById(id);
//
//	 return ResponseEntity.ok("Deleted");
//
//	}
	

	
	@PutMapping("/updateProductionPlanningChangeOverPlan")
	public ResponseEntity<?> updateProductionPlanningChangeOverPlan(
	        @RequestBody ProductionPlanningChangeoverPlan dto) {

	    ProductionPlanningChangeoverPlan plan =
	    		productionPlanningChangeoverPlanRepositoryObject.findById(dto.getChangeoverId())
	        .orElseThrow(() -> new RuntimeException("Invalid ID"));

	    plan.setArticle(dto.getArticle());
	    plan.setMouldName(dto.getMouldName());
	    plan.setDuplicateMouldName(dto.getDuplicateMouldName());
	    plan.setBatchCode(dto.getBatchCode());
	    plan.setPlannedShots(dto.getPlannedShots());
	    plan.setPriority(dto.getPriority());
	    plan.setPlannedDate(dto.getPlannedDate());
	    
	    plan.setPlannedDate(dateTimeService.getCurrentDateAndTime());
	
	    productionPlanningChangeoverPlanRepositoryObject.save(plan);

	    return ResponseEntity.ok("Updated Successfully");
	}
	
	
	

	
	@Transactional
	@DeleteMapping("/deletePlan/{machineName}/{plannedDate}/{planType}")
	public ResponseEntity<?> deletePlan(
	        @PathVariable String machineName,
	        @PathVariable String plannedDate,
	        @PathVariable String planType) {

	    if (planType.equalsIgnoreCase("all")) {
	    	productionPlanningRepositoryObject
	            .deleteByMachineNameAndPlannedDate(machineName, plannedDate);

	        return ResponseEntity.ok("All plans deleted for date " + plannedDate);
	    }

	    productionPlanningRepositoryObject
	        .deleteByMachineNameAndPlannedDateAndPlanType(machineName, plannedDate, planType);

	    return ResponseEntity.ok(planType + " deleted for date " + plannedDate);
	}
	
	
	@GetMapping("/getAutoGeneratedMixingMill/{planId}")
	public ResponseEntity<?> getAutoGeneratedMixingMill(
	        @PathVariable String planId){

	    return ResponseEntity.ok(
	        planningAutoGenerateMixingMillAndProductionRepository
	            .findByPlanIdAndType(planId,"M")
	    );

	}
	
	@GetMapping("/getAutoGeneratedProduction/{planId}")
	public ResponseEntity<?> getAutoGeneratedProduction(
	        @PathVariable String planId){

	    return ResponseEntity.ok(
	        planningAutoGenerateMixingMillAndProductionRepository
	            .findByPlanIdAndType(planId,"P")
	    );

	}

}




