package web.minda.project.dto;

import java.util.List;

public class AutoGeneratedPlanDTO {

    private Long changeoverId;

    private List<MixingmillRowDTO> mixingmillList;
    private List<BatchCuttingRowDTO> batchCuttingList;
    private List<ProductionRowDTO> productionList;
    
    private List<MachinePlanDTO> machinePlans;
    
    private String plannedDate;
    
    

    public String getPlannedDate() {
		return plannedDate;
	}

	public void setPlannedDate(String plannedDate) {
		this.plannedDate = plannedDate;
	}

	public List<MachinePlanDTO> getMachinePlans() {
		return machinePlans;
	}

	public void setMachinePlans(List<MachinePlanDTO> machinePlans) {
		this.machinePlans = machinePlans;
	}

	public Long getChangeoverId() {
        return changeoverId;
    }

    public void setChangeoverId(Long changeoverId) {
        this.changeoverId = changeoverId;
    }

    public List<MixingmillRowDTO> getMixingmillList() {
        return mixingmillList;
    }

    public void setMixingmillList(List<MixingmillRowDTO> mixingmillList) {
        this.mixingmillList = mixingmillList;
    }

    public List<BatchCuttingRowDTO> getBatchCuttingList() {
        return batchCuttingList;
    }

    public void setBatchCuttingList(List<BatchCuttingRowDTO> batchCuttingList) {
        this.batchCuttingList = batchCuttingList;
    }

    public List<ProductionRowDTO> getProductionList() {
        return productionList;
    }

    public void setProductionList(List<ProductionRowDTO> productionList) {
        this.productionList = productionList;
    }
}