package web.minda.project.dto;

public interface ProductionPlanningDTO {
	
	 Long productionPlanningId();
	
	Long getChangeoverId();

	String getMachineName();

	String getTonnage();

	String getMachineStatus();

	String getArticle();

	String getMouldName();

	String getPlannedShots();

	String getTargetShots();

	String getCurrentShots();

	String getPriority();

	String getStartTime();

	String getSequenceNo();
	
	String getRunningStatus();
	
	String getDuplicateMouldName();
	
	String getBatchCode();
	
	String getPlannedDate();
	
	String getPendingShots();
	
     String getPlanType();
     
     String getAutoGeneratedSaved();
     
     String getPlanId();
     
     String getSourceType();
     
     
}
