package web.minda.project.repositories;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import web.minda.project.dto.ProductionPlanningDTO;
import web.minda.project.entity.MouldMaster;
import web.minda.project.entity.ProductionPlanning;
import web.minda.project.entity.ProductionPlanningChangeoverPlan;
import web.minda.project.entity.MouldMaster;

public interface ProductionPlanningRepository extends JpaRepository<ProductionPlanning, Long> {

	Optional<ProductionPlanning> findByMachineName(String machineName);

	Optional<ProductionPlanning> findByPlanId(String planId);

	Optional<ProductionPlanning> findByPlanIdAndPlanType(String planId, String planType);

	Optional<ProductionPlanning> findByMachineNameAndArticleAndPlannedDate(String machineName, String article,
			String plannedDate);

	void deleteByMachineName(String machineName);

	void deleteByMachineNameAndPlanType(String machineName, String planType);

	void deleteByMachineNameAndPlannedDate(String machineName, String plannedDate);

	void deleteByMachineNameAndPlannedDateAndPlanType(String machineName, String plannedDate, String planType);

	Optional<ProductionPlanning> findFirstByPlanIdAndPlanType(String planId, String planType);

//	
//	@Query(value = """
//
//		    SELECT
//		        mm.machine_name AS machineName,
//		        mm.tonnage AS tonnage,
//		        mm.status AS machineStatus,
//
//		        cpp.id AS changeoverId,
//		        cpp.sequence_no AS sequenceNo,
//		        cpp.article AS article,
//		        cpp.mould_name AS mouldName,
//		        pp.actual_shots AS currentShots,
//		        cpp.planned_shots AS targetShots,
//		        cpp.priority AS priority,
//		        cpp.status AS runningStatus,
//		        pp.priority AS runningPriority,
//		        cpp.duplicate_mould_name AS duplicateMouldName,
//		        cpp.batch_code AS batchCode,
//		        cpp.pending_shots AS pendingShots,
//		        cpp.plan_type AS planType,
//		        cpp.auto_generated_saved AS autoGeneratedSaved,
//		        cpp.planned_date AS plannedDate
//		      
//
//		    FROM machine_master mm
//
//		  LEFT JOIN production_planning pp
//    ON mm.machine_name = pp.machine_name
//    AND TRY_CONVERT(DATE, pp.date_time_creation) = CAST(GETDATE() AS DATE)
//
//	LEFT JOIN production_planning_changeover_plan cpp
//ON mm.machine_name = cpp.machine_name
//
//
//		    WHERE
//		        (
//		            (:machineName IS NULL OR :machineName = ''
//		                OR mm.machine_name LIKE CONCAT('%', :machineName, '%'))
//
//		            AND (:article IS NULL OR :article = ''
//		                OR cpp.article LIKE CONCAT('%', :article, '%'))
//		        )
//
//		        AND (:status IS NULL OR :status = ''
//		            OR cpp.status LIKE CONCAT('%', :status, '%'))
//
//		        AND (:priority IS NULL OR :priority = ''
//		            OR cpp.priority LIKE CONCAT('%', :priority, '%'))
//		            
//
//
//		    ORDER BY
//		        mm.machine_name,
//
//		        CASE cpp.priority
//		            WHEN 'Urgent' THEN 0
//		            WHEN 'High' THEN 1
//		            WHEN 'Medium' THEN 2
//		            WHEN 'Low' THEN 3
//		            WHEN 'Hold' THEN 4
//		            ELSE 5
//		        END,
//
//		        cpp.sequence_no
//
//		""",
//
//		countQuery = """
//
//		    SELECT COUNT(*)
//		    FROM machine_master mm
//
//		    LEFT JOIN production_planning pp
//		        ON mm.machine_name = pp.machine_name
//		        AND TRY_CONVERT(DATE, pp.date_time_creation) = CAST(GETDATE() AS DATE)
//		        
//LEFT JOIN production_planning_changeover_plan cpp
//ON mm.machine_name = cpp.machine_name
//
//
//		    WHERE
//		        (
//		            (:machineName IS NULL OR :machineName = ''
//		                OR mm.machine_name LIKE CONCAT('%', :machineName, '%'))
//
//		            AND (:article IS NULL OR :article = ''
//		                OR cpp.article LIKE CONCAT('%', :article, '%'))
//		        )
//
//		        AND (:status IS NULL OR :status = ''
//		            OR cpp.status LIKE CONCAT('%', :status, '%'))
//
//		        AND (:priority IS NULL OR :priority = ''
//		            OR cpp.priority LIKE CONCAT('%', :priority, '%'))
//		            
//
//
//		""",
//
//		nativeQuery = true)
//		Page<ProductionPlanningDTO> getLikeProductionPlanning(
//		    @Param("machineName") String machineName,
//		    @Param("article") String article,
//		    @Param("status") String status,
//		    @Param("priority") String priority,
//		  
//		    Pageable pageable
//		);
//	

	@Query(value = """

			    		SELECT


			    		mm.machine_name AS machineName,
			    		mm.tonnage AS tonnage,
			    		mm.status AS machineStatus,


			    		pp.id AS productionPlanningId,

			    		cpp.id AS changeoverId,


			    		CASE

			    		WHEN pp.id IS NOT NULL

			    		THEN 'PRODUCTION'

			    		ELSE 'CHANGEOVER'

			    		END AS sourceType,



			    		COALESCE(pp.article, cpp.article) AS article,

			    		COALESCE(pp.mould_name, cpp.mould_name) AS mouldName,

			    		COALESCE(pp.duplicate_mould_name, cpp.duplicate_mould_name) AS duplicateMouldName,

			    		COALESCE(pp.batch_code, cpp.batch_code) AS batchCode,


			    		COALESCE(pp.planned_shots, cpp.planned_shots) AS targetShots,


			    		pp.actual_shots AS currentShots,


			    		COALESCE(pp.priority, cpp.priority) AS priority,


			    		COALESCE(pp.status, cpp.status) AS runningStatus,


			    		COALESCE(pp.plan_type, cpp.plan_type) AS planType,


			    		cpp.sequence_no AS sequenceNo,


			    		cpp.pending_shots AS pendingShots,


			    		cpp.auto_generated_saved AS autoGeneratedSaved,


			    		COALESCE(pp.planned_date, cpp.planned_date) AS plannedDate,


			    		pp.plan_id AS planId



			    		FROM machine_master mm



			    		LEFT JOIN production_planning pp


			    		ON pp.machine_name = mm.machine_name


			    		AND


			    		CAST(pp.planned_date AS DATE)

			    		=

			    	CAST(
			COALESCE(
			NULLIF(:plannedDate,''),
			CONVERT(varchar(10),GETDATE(),120)
			)
			AS DATE)

			    		LEFT JOIN production_planning_changeover_plan cpp


			    		ON cpp.machine_name = mm.machine_name



			    		AND


			    		(
			    		pp.id IS NULL

			    		OR

			    		cpp.plan_type = pp.plan_type

			    		)





			    		WHERE



			    		(
			    		:machineName IS NULL

			    		OR :machineName=''

			    		OR mm.machine_name LIKE CONCAT('%',:machineName,'%')

			    		)




			    		AND


			    		(
			    		:article IS NULL

			    		OR :article=''

			    		OR COALESCE(pp.article,cpp.article)

			    		LIKE CONCAT('%',:article,'%')

			    		)




			    		AND


			    		(
			    		:status IS NULL

			    		OR :status=''

			    		OR COALESCE(pp.status,cpp.status)

			    		LIKE CONCAT('%',:status,'%')

			    		)




			    		AND


			    		(
			    		:priority IS NULL

			    		OR :priority=''

			    		OR COALESCE(pp.priority,cpp.priority)

			    		LIKE CONCAT('%',:priority,'%')

			    		)



			    		ORDER BY


			    		mm.machine_name,


			    		CASE COALESCE(pp.plan_type,cpp.plan_type)

			    		WHEN 'main' THEN 1

			    		WHEN 'next' THEN 2

			    		WHEN 'spare' THEN 3

			    		ELSE 4

			    		END



			    		""",

			countQuery = """

					    		SELECT COUNT(*)


					    		FROM machine_master mm



					    		LEFT JOIN production_planning pp


					    		ON pp.machine_name = mm.machine_name


					    		AND


					    		CAST(pp.planned_date AS DATE)

					    		=

					    		CAST(
					COALESCE(
					NULLIF(:plannedDate,''),
					CONVERT(varchar(10),GETDATE(),120)
					)
					AS DATE)





					    		LEFT JOIN production_planning_changeover_plan cpp


					    		ON cpp.machine_name = mm.machine_name



					    		AND


					    		(
					    		pp.id IS NULL

					    		OR cpp.plan_type = pp.plan_type

					    		)





					    		WHERE



					    		(
					    		:machineName IS NULL

					    		OR :machineName=''

					    		OR mm.machine_name LIKE CONCAT('%',:machineName,'%')

					    		)




					    		AND


					    		(
					    		:article IS NULL

					    		OR :article=''

					    		OR COALESCE(pp.article,cpp.article)

					    		LIKE CONCAT('%',:article,'%')

					    		)




					    		AND


					    		(
					    		:status IS NULL

					    		OR :status=''

					    		OR COALESCE(pp.status,cpp.status)

					    		LIKE CONCAT('%',:status,'%')

					    		)




					    		AND


					    		(
					    		:priority IS NULL

					    		OR :priority=''

					    		OR COALESCE(pp.priority,cpp.priority)

					    		LIKE CONCAT('%',:priority,'%')

					    		)


					    		""",

			nativeQuery = true)
	Page<ProductionPlanningDTO> getLikeProductionPlanning(

			@Param("machineName") String machineName,

			@Param("article") String article,

			@Param("status") String status,

			@Param("priority") String priority,

			@Param("plannedDate") String plannedDate,

			Pageable pageable

	);

	// 30-06-2026 before change

//    @Query(value = """
//
//    	    SELECT
//
//    	        mm.machine_name AS machineName,
//
//    	        mm.tonnage AS tonnage,
//
//    	        mm.status AS machineStatus,
//
//
//    	        cpp.id AS changeoverId,
//
//    	        cpp.sequence_no AS sequenceNo,
//
//    	        cpp.article AS article,
//
//    	        cpp.mould_name AS mouldName,
//
//
//    	        pp.actual_shots AS currentShots,
//
//    	        cpp.planned_shots AS targetShots,
//
//
//    	        cpp.priority AS priority,
//
//    	        cpp.status AS runningStatus,
//
//
//    	        pp.priority AS runningPriority,
//
//
//    	        cpp.duplicate_mould_name AS duplicateMouldName,
//
//
//    	        cpp.batch_code AS batchCode,
//
//
//    	        cpp.pending_shots AS pendingShots,
//
//
//    	        cpp.plan_type AS planType,
//
//
//    	        cpp.auto_generated_saved AS autoGeneratedSaved,
//
//
//    	        pp.planned_date AS plannedDate,
//
//    	        pp.plan_id AS planId
//
//
//
//    	    FROM machine_master mm
//
//
//
//    	    OUTER APPLY
//    	    (
//
//    	        SELECT TOP 1
//                    p.id AS productionPlanningId,
//
//    	            p.actual_shots,
//
//    	            p.priority,
//
//    	            p.plan_id,
//
//    	            p.planned_date
//
//
//
//    	        FROM production_planning p
//
//
//
//    	        WHERE
//
//    	            p.machine_name = mm.machine_name
//
//
//    	            AND TRY_CONVERT(DATE,p.date_time_creation)
//    	                = CAST(GETDATE() AS DATE)
//
//
//
//    	        ORDER BY
//
//    	            p.id DESC
//
//
//
//    	    ) pp
//
//
//
//
//
//    	    LEFT JOIN production_planning_changeover_plan cpp
//
//
//    	    ON mm.machine_name = cpp.machine_name
//
//
//
//
//
//    	    WHERE
//
//
//
//    	        (
//
//    	            (:machineName IS NULL OR :machineName = ''
//
//
//    	            OR mm.machine_name LIKE CONCAT('%', :machineName, '%'))
//
//
//
//    	            AND
//
//
//
//    	            (:article IS NULL OR :article = ''
//
//
//    	            OR cpp.article LIKE CONCAT('%', :article, '%'))
//
//
//    	        )
//
//
//
//    	        AND
//
//
//
//    	        (:status IS NULL OR :status = ''
//
//
//    	        OR cpp.status LIKE CONCAT('%', :status, '%'))
//
//
//
//
//    	        AND
//
//
//
//    	        (:priority IS NULL OR :priority = ''
//
//
//    	        OR cpp.priority LIKE CONCAT('%', :priority, '%'))
//
//
//
//
//
//    	    ORDER BY
//
//
//
//    	        mm.machine_name,
//
//
//
//    	        CASE cpp.priority
//
//
//    	            WHEN 'Urgent' THEN 0
//
//
//    	            WHEN 'High' THEN 1
//
//
//    	            WHEN 'Medium' THEN 2
//
//
//    	            WHEN 'Low' THEN 3
//
//
//    	            WHEN 'Hold' THEN 4
//
//
//    	            ELSE 5
//
//
//    	        END,
//
//
//
//    	        cpp.sequence_no
//
//
//
//    	""",
//
//
//    	countQuery = """
//
//    	    SELECT COUNT(*)
//    	    FROM machine_master mm
//
//    	    OUTER APPLY
//
//    	    (
//
//    	        SELECT TOP 1
//    	          p.id
//    	        FROM production_planning p
//    	        WHERE
//    	            p.machine_name = mm.machine_name
//
//    	            AND TRY_CONVERT(DATE,p.date_time_creation)
//
//    	                = CAST(GETDATE() AS DATE)
//    	        ORDER BY
//
//
//    	            p.id DESC
//
//    	    ) pp
//
//    	    LEFT JOIN production_planning_changeover_plan cpp
//
//    	    ON mm.machine_name = cpp.machine_name
//
//    	    WHERE
//
//    	        (
//
//    	            (:machineName IS NULL OR :machineName = ''
//    	            OR mm.machine_name LIKE CONCAT('%', :machineName, '%'))
//
//    	            AND
//    	            (:article IS NULL OR :article = ''
//    	            OR cpp.article LIKE CONCAT('%', :article, '%'))
//
//    	        )
//
//    	        AND
//    	        (:status IS NULL OR :status = ''
//
//    	        OR cpp.status LIKE CONCAT('%', :status, '%'))
//
//    	        AND
//    	        (:priority IS NULL OR :priority = ''
//
//    	        OR cpp.priority LIKE CONCAT('%', :priority, '%'))
//    	""",
//
//    	nativeQuery = true)
//
//    	Page<ProductionPlanningDTO> getLikeProductionPlanning(
//
//    	    @Param("machineName") String machineName,
//
//    	    @Param("article") String article,
//
//    	    @Param("status") String status,
//
//    	    @Param("priority") String priority,
//
//
//    	    Pageable pageable
//
//    	);

	Optional<ProductionPlanning> findByPlanIdAndMachineNameAndPlanType(String planId, String machineName,
			String string);

//    @Query(value = """
//
//    	    SELECT
//    	        mm.machine_name AS machineName,
//    	        mm.tonnage AS tonnage,
//    	        mm.status AS machineStatus,
//
//    	        cpp.id AS changeoverId,
//    	        cpp.sequence_no AS sequenceNo,
//    	        cpp.article AS article,
//    	        cpp.mould_name AS mouldName,
//
//    	        pp.actual_shots AS currentShots,
//
//    	        cpp.planned_shots AS targetShots,
//
//    	        cpp.priority AS priority,
//    	        cpp.status AS runningStatus,
//
//    	        pp.priority AS runningPriority,
//
//    	        cpp.duplicate_mould_name AS duplicateMouldName,
//
//    	        cpp.batch_code AS batchCode,
//
//    	        cpp.pending_shots AS pendingShots,
//
//    	        cpp.plan_type AS planType,
//
//    	        cpp.auto_generated_saved AS autoGeneratedSaved,
//
//    	        cpp.planned_date AS plannedDate,
//
//    	        pp.plan_id AS planId
//
//
//    	    FROM machine_master mm
//
//
//
//    	    OUTER APPLY
//    	    (
//    	        SELECT TOP 1
//
//    	            p.actual_shots,
//    	            p.priority,
//    	            p.plan_id
//
//    	        FROM production_planning p
//
//    	        WHERE 
//    	            p.machine_name = mm.machine_name
//
//    	            AND TRY_CONVERT(DATE,p.date_time_creation)
//    	                = CAST(GETDATE() AS DATE)
//
//    	        ORDER BY 
//    	            p.id DESC
//
//
//    	    ) pp
//
//
//
//    	    LEFT JOIN production_planning_changeover_plan cpp
//
//    	    ON mm.machine_name = cpp.machine_name
//
//
//
//    	    WHERE
//
//    	        (
//    	            (:machineName IS NULL OR :machineName = ''
//    	                OR mm.machine_name LIKE CONCAT('%', :machineName, '%'))
//
//    	            AND
//
//    	            (:article IS NULL OR :article = ''
//    	                OR cpp.article LIKE CONCAT('%', :article, '%'))
//    	        )
//
//
//    	        AND
//
//    	        (:status IS NULL OR :status = ''
//    	            OR cpp.status LIKE CONCAT('%', :status, '%'))
//
//
//    	        AND
//
//    	        (:priority IS NULL OR :priority = ''
//    	            OR cpp.priority LIKE CONCAT('%', :priority, '%'))
//
//
//
//    	    ORDER BY
//
//    	        mm.machine_name,
//
//
//    	        CASE cpp.priority
//
//    	            WHEN 'Urgent' THEN 0
//    	            WHEN 'High' THEN 1
//    	            WHEN 'Medium' THEN 2
//    	            WHEN 'Low' THEN 3
//    	            WHEN 'Hold' THEN 4
//    	            ELSE 5
//
//    	        END,
//
//
//    	        cpp.sequence_no
//
//
//
//    	""",
//
//    	countQuery = """
//
//    	    SELECT COUNT(*)
//
//    	    FROM machine_master mm
//
//
//
//    	    OUTER APPLY
//    	    (
//    	        SELECT TOP 1
//
//    	            p.id
//
//    	        FROM production_planning p
//
//    	        WHERE
//
//    	            p.machine_name = mm.machine_name
//
//    	            AND TRY_CONVERT(DATE,p.date_time_creation)
//    	                = CAST(GETDATE() AS DATE)
//
//    	        ORDER BY 
//    	            p.id DESC
//
//    	    ) pp
//
//
//
//    	    LEFT JOIN production_planning_changeover_plan cpp
//
//    	    ON mm.machine_name = cpp.machine_name
//
//
//
//    	    WHERE
//
//    	        (
//    	            (:machineName IS NULL OR :machineName = ''
//    	                OR mm.machine_name LIKE CONCAT('%', :machineName, '%'))
//
//    	            AND
//
//    	            (:article IS NULL OR :article = ''
//    	                OR cpp.article LIKE CONCAT('%', :article, '%'))
//    	        )
//
//
//    	        AND
//
//    	        (:status IS NULL OR :status = ''
//    	            OR cpp.status LIKE CONCAT('%', :status, '%'))
//
//
//    	        AND
//
//    	        (:priority IS NULL OR :priority = ''
//    	            OR cpp.priority LIKE CONCAT('%', :priority, '%'))
//
//
//
//    	""",
//
//    	nativeQuery = true)
//
//    	Page<ProductionPlanningDTO> getLikeProductionPlanning(
//
//    	    @Param("machineName") String machineName,
//
//    	    @Param("article") String article,
//
//    	    @Param("status") String status,
//
//    	    @Param("priority") String priority,
//
//    	    Pageable pageable
//
//    	);
//    
//	

//	@Query(value = """
//
//		    SELECT
//		        mm.machine_name AS machineName,
//		        mm.tonnage AS tonnage,
//		        mm.status AS machineStatus,
//
//		        cpp.id AS changeoverId,
//		        cpp.sequence_no AS sequenceNo,
//		        cpp.article AS article,
//		        cpp.mould_name AS mouldName,
//		        pp.actual_shots AS currentShots,
//		        cpp.planned_shots AS targetShots,
//		        cpp.priority AS priority,
//		        cpp.status AS runningStatus,
//		        pp.priority AS runningPriority,
//		        cpp.duplicate_mould_name AS duplicateMouldName,
//		        cpp.batch_code AS batchCode,
//		        cpp.pending_shots AS pendingShots,
//		        cpp.plan_type AS planType,
//		        cpp.auto_generated_saved AS autoGeneratedSaved,
//		        cpp.planned_date AS plannedDate
//		      
//
//		    FROM machine_master mm
//
//		  LEFT JOIN production_planning pp
//    ON mm.machine_name = pp.machine_name
//    AND TRY_CONVERT(DATE, pp.date_time_creation) = CAST(GETDATE() AS DATE)
//
//	LEFT JOIN production_planning_changeover_plan cpp
//ON mm.machine_name = cpp.machine_name
//AND (
//     :dateTime IS NULL
//     OR :dateTime=''
//     OR CAST(cpp.planned_date AS DATE)=CAST(:dateTime AS DATE)
//)
//
//		    WHERE
//		        (
//		            (:machineName IS NULL OR :machineName = ''
//		                OR mm.machine_name LIKE CONCAT('%', :machineName, '%'))
//
//		            AND (:article IS NULL OR :article = ''
//		                OR cpp.article LIKE CONCAT('%', :article, '%'))
//		        )
//
//		        AND (:status IS NULL OR :status = ''
//		            OR cpp.status LIKE CONCAT('%', :status, '%'))
//
//		        AND (:priority IS NULL OR :priority = ''
//		            OR cpp.priority LIKE CONCAT('%', :priority, '%'))
//		            
//
//
//		    ORDER BY
//		        mm.machine_name,
//
//		        CASE cpp.priority
//		            WHEN 'Urgent' THEN 0
//		            WHEN 'High' THEN 1
//		            WHEN 'Medium' THEN 2
//		            WHEN 'Low' THEN 3
//		            WHEN 'Hold' THEN 4
//		            ELSE 5
//		        END,
//
//		        cpp.sequence_no
//
//		""",
//
//		countQuery = """
//
//		    SELECT COUNT(*)
//		    FROM machine_master mm
//
//		    LEFT JOIN production_planning pp
//		        ON mm.machine_name = pp.machine_name
//		        AND TRY_CONVERT(DATE, pp.date_time_creation) = CAST(GETDATE() AS DATE)
//		        
//LEFT JOIN production_planning_changeover_plan cpp
//ON mm.machine_name = cpp.machine_name
//AND (
//     :dateTime IS NULL
//     OR :dateTime=''
//     OR CAST(cpp.planned_date AS DATE)=CAST(:dateTime AS DATE)
//)
//
//		    WHERE
//		        (
//		            (:machineName IS NULL OR :machineName = ''
//		                OR mm.machine_name LIKE CONCAT('%', :machineName, '%'))
//
//		            AND (:article IS NULL OR :article = ''
//		                OR cpp.article LIKE CONCAT('%', :article, '%'))
//		        )
//
//		        AND (:status IS NULL OR :status = ''
//		            OR cpp.status LIKE CONCAT('%', :status, '%'))
//
//		        AND (:priority IS NULL OR :priority = ''
//		            OR cpp.priority LIKE CONCAT('%', :priority, '%'))
//		            
//
//
//		""",
//
//		nativeQuery = true)
//		Page<ProductionPlanningDTO> getLikeProductionPlanning(
//		    @Param("machineName") String machineName,
//		    @Param("article") String article,
//		    @Param("status") String status,
//		    @Param("priority") String priority,
//		    @Param("dateTime") String dateTime,
//		    Pageable pageable
//		);

//	Optional<ProductionPlanning> findByChangeoverId(Long changeoverId);

//	Optional<ProductionPlanning> findByChangeoverId(Long changeoverId);

//	@Query(value = """
//
//		    SELECT
//		        mm.machine_name AS machineName,
//		        mm.tonnage AS tonnage,
//		        mm.status AS machineStatus,
//
//		        cpp.id AS changeoverId,
//		        cpp.sequence_no AS sequenceNo,
//		        cpp.article AS article,
//		        cpp.mould_name AS mouldName,
//		        pp.actual_shots AS currentShots,
//		        cpp.planned_shots AS targetShots,
//		        cpp.priority AS priority,
//		        cpp.status AS runningStatus,
//		        pp.priority AS runningPriority,
//		        cpp.duplicate_mould_name AS duplicateMouldName,
//		        cpp.batch_code AS batchCode,
//		        cpp.pending_shots AS pendingShots,
//		        cpp.plan_type AS planType,
//		        cpp.auto_generated_saved AS autoGeneratedSaved,
//		        cpp.planned_date AS plannedDate
//		      
//
//		    FROM machine_master mm
//
//		  LEFT JOIN production_planning pp
//    ON mm.machine_name = pp.machine_name
//    AND TRY_CONVERT(DATE, pp.date_time_creation) = CAST(GETDATE() AS DATE)
//
//		    LEFT JOIN production_planning_changeover_plan cpp
//		        ON mm.machine_name = cpp.machine_name
//		        AND CAST(cpp.planned_date AS DATE) = CAST(GETDATE() AS DATE)
//
//		    WHERE
//		        (
//		            (:machineName IS NULL OR :machineName = ''
//		                OR mm.machine_name LIKE CONCAT('%', :machineName, '%'))
//
//		            AND (:article IS NULL OR :article = ''
//		                OR cpp.article LIKE CONCAT('%', :article, '%'))
//		        )
//
//		        AND (:status IS NULL OR :status = ''
//		            OR cpp.status LIKE CONCAT('%', :status, '%'))
//
//		        AND (:priority IS NULL OR :priority = ''
//		            OR cpp.priority LIKE CONCAT('%', :priority, '%'))
//		            
//		            AND (
//    :dateTime IS NULL
//    OR :dateTime = ''
//    OR CAST(cpp.planned_date AS DATE) = CAST(:dateTime AS DATE)
//)
//
//		    ORDER BY
//		        mm.machine_name,
//
//		        CASE cpp.priority
//		            WHEN 'Urgent' THEN 0
//		            WHEN 'High' THEN 1
//		            WHEN 'Medium' THEN 2
//		            WHEN 'Low' THEN 3
//		            WHEN 'Hold' THEN 4
//		            ELSE 5
//		        END,
//
//		        cpp.sequence_no
//
//		""",
//
//		countQuery = """
//
//		    SELECT COUNT(*)
//		    FROM machine_master mm
//
//		    LEFT JOIN production_planning pp
//		        ON mm.machine_name = pp.machine_name
//		        AND TRY_CONVERT(DATE, pp.date_time_creation) = CAST(GETDATE() AS DATE)
//
//		    LEFT JOIN production_planning_changeover_plan cpp
//		        ON mm.machine_name = cpp.machine_name
//		        AND CAST(cpp.planned_date AS DATE) = CAST(GETDATE() AS DATE)
//
//		    WHERE
//		        (
//		            (:machineName IS NULL OR :machineName = ''
//		                OR mm.machine_name LIKE CONCAT('%', :machineName, '%'))
//
//		            AND (:article IS NULL OR :article = ''
//		                OR cpp.article LIKE CONCAT('%', :article, '%'))
//		        )
//
//		        AND (:status IS NULL OR :status = ''
//		            OR cpp.status LIKE CONCAT('%', :status, '%'))
//
//		        AND (:priority IS NULL OR :priority = ''
//		            OR cpp.priority LIKE CONCAT('%', :priority, '%'))
//		            
//		            		            AND (
//    :dateTime IS NULL
//    OR :dateTime = ''
//    OR CAST(cpp.planned_date AS DATE) = CAST(:dateTime AS DATE)
//)
//
//		""",
//
//		nativeQuery = true)
//		Page<ProductionPlanningDTO> getLikeProductionPlanning(
//		    @Param("machineName") String machineName,
//		    @Param("article") String article,
//		    @Param("status") String status,
//		    @Param("priority") String priority,
//		    @Param("dateTime") String dateTime,
//		    Pageable pageable
//		);
//	
//	

//	@Query(value = """
//						SELECT
//						    mm.machine_name AS machineName,
//						    mm.tonnage AS tonnage,
//						    mm.status AS machineStatus,
//
//							cpp.id AS changeoverId,
//						    cpp.sequence_no AS sequenceNo,
//						    cpp.article AS article,
//						    cpp.mould_name AS mouldName,
//						    pp.actual_shots AS currentShots,
//							cpp.planned_shots AS targetShots,
//						    cpp.priority AS priority,
//						    cpp.status AS runningStatus,
//							pp.priority AS runningPriority,
//							cpp.duplicate_mould_name AS duplicateMouldName,
//							cpp.batch_code AS batchCode,
//							cpp.pending_shots AS pendingShots,
//							cpp.plan_type AS planType
//
//						FROM machine_master mm
//
//						LEFT JOIN production_planning pp
//						    ON mm.machine_name = pp.machine_name
//
//						LEFT JOIN production_planning_changeover_plan cpp
//						    ON mm.machine_name = cpp.machine_name
//
//						WHERE
//						    ((:machineName IS NULL OR :machineName = ''
//						        OR mm.machine_name LIKE CONCAT('%', :machineName, '%'))
//			
//						AND (:article IS NULL OR :article = ''
//						        OR cpp.article LIKE CONCAT('%', :article, '%')))
//			
//						AND (:status IS NULL OR :status = ''
//						        OR cpp.status LIKE CONCAT('%', :status, '%'))
//			
//						AND (:priority IS NULL OR :priority = ''
//						        OR cpp.priority LIKE CONCAT('%', :priority, '%'))
//						        
//						    
//
//						ORDER BY
//						    mm.machine_name,
//			
//						    CASE cpp.priority
//						        WHEN 'Urgent' THEN 0
//						        WHEN 'High' THEN 1
//						        WHEN 'Medium' THEN 2
//						        WHEN 'Low' THEN 3
//						        WHEN 'Hold' THEN 4
//						        ELSE 4
//						    END,
//			
//						    cpp.sequence_no
//			""",
//
//			countQuery = """
//					SELECT COUNT(*)
//					FROM machine_master mm
//
//						LEFT JOIN production_planning pp
//						    ON mm.machine_name = pp.machine_name
//
//						LEFT JOIN production_planning_changeover_plan cpp
//						    ON mm.machine_name = cpp.machine_name
//
//						WHERE
//						    ((:machineName IS NULL OR :machineName = ''
//						        OR mm.machine_name LIKE CONCAT('%', :machineName, '%'))
//			
//						AND (:article IS NULL OR :article = ''
//						        OR cpp.article LIKE CONCAT('%', :article, '%')))
//			
//						AND (:status IS NULL OR :status = ''
//						        OR cpp.status LIKE CONCAT('%', :status, '%'))
//			
//						AND (:priority IS NULL OR :priority = ''
//						        OR cpp.priority LIKE CONCAT('%', :priority, '%'))
//
//					""",
//
//			nativeQuery = true)
//	Page<ProductionPlanningDTO> getLikeProductionPlanning(@Param("machineName") String machineName,
//			@Param("article") String article, @Param("status") String status, @Param("priority") String priority,
//			Pageable pageable);
//	

	// AND cpp.planned_date = CONVERT(VARCHAR(10), GETDATE(), 23)

}
