package web.minda.project.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


@Entity
@Table(name = "production_Mixing_Mill")
public class ProductionMixingmilAutoGenerated {
	
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	private Long productionMixingMillId;
	
	@Column(name = "article")
	private String article;
	
	@Column(name = "mould")
	private String mould;
	
	@Column(name = "compound")
	private String compound;
	
	@Column(name = "batch_weight")
	private String batchWeight;
	
	@Column(name = "shots_per_day")
	private String shotsPerDay;
	
	@Column(name = "per_shot_weight_kg")
	private String perShotWeightKG;
	
	@Column(name = "total_weight_kg")
	private String totalWeightKG;
	
	@Column(name = "suggestive_batch")
	private String suggestiveBatch;
	
	@Column(name = "article_batch")
	private String actualBatch;
	
	@Column(name = "status")
	private String status;

	@Column(name = "created_by")
	private String createdBy;

	@Column(name = "date_time_creation")
	private String dateTimeCreation;

	@Column(name = "date_time_modified")
	private String dateTimeModified;


	@Column(name = "changeover_id")
	private Long changeoverId;


	public String getArticle() {
		return article;
	}


	public void setArticle(String article) {
		this.article = article;
	}


	public String getMould() {
		return mould;
	}


	public void setMould(String mould) {
		this.mould = mould;
	}


	public String getCompound() {
		return compound;
	}


	public void setCompound(String compound) {
		this.compound = compound;
	}


	public String getBatchWeight() {
		return batchWeight;
	}


	public void setBatchWeight(String batchWeight) {
		this.batchWeight = batchWeight;
	}


	public String getShotsPerDay() {
		return shotsPerDay;
	}


	public void setShotsPerDay(String shotsPerDay) {
		this.shotsPerDay = shotsPerDay;
	}


	public String getPerShotWeightKG() {
		return perShotWeightKG;
	}


	public void setPerShotWeightKG(String perShotWeightKG) {
		this.perShotWeightKG = perShotWeightKG;
	}


	public String getTotalWeightKG() {
		return totalWeightKG;
	}


	public void setTotalWeightKG(String totalWeightKG) {
		this.totalWeightKG = totalWeightKG;
	}


	public String getSuggestiveBatch() {
		return suggestiveBatch;
	}


	public void setSuggestiveBatch(String suggestiveBatch) {
		this.suggestiveBatch = suggestiveBatch;
	}


	public String getActualBatch() {
		return actualBatch;
	}


	public void setActualBatch(String actualBatch) {
		this.actualBatch = actualBatch;
	}


	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}


	public String getCreatedBy() {
		return createdBy;
	}


	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}


	public String getDateTimeCreation() {
		return dateTimeCreation;
	}


	public void setDateTimeCreation(String dateTimeCreation) {
		this.dateTimeCreation = dateTimeCreation;
	}


	public String getDateTimeModified() {
		return dateTimeModified;
	}


	public void setDateTimeModified(String dateTimeModified) {
		this.dateTimeModified = dateTimeModified;
	}


	public Long getChangeoverId() {
		return changeoverId;
	}


	public void setChangeoverId(Long changeoverId) {
		this.changeoverId = changeoverId;
	}


	public ProductionMixingmilAutoGenerated(String article, String mould, String compound, String batchWeight,
			String shotsPerDay, String perShotWeightKG, String totalWeightKG, String suggestiveBatch,
			String actualBatch, String status, String createdBy, String dateTimeCreation, String dateTimeModified,
			Long changeoverId) {
		super();
		this.article = article;
		this.mould = mould;
		this.compound = compound;
		this.batchWeight = batchWeight;
		this.shotsPerDay = shotsPerDay;
		this.perShotWeightKG = perShotWeightKG;
		this.totalWeightKG = totalWeightKG;
		this.suggestiveBatch = suggestiveBatch;
		this.actualBatch = actualBatch;
		this.status = status;
		this.createdBy = createdBy;
		this.dateTimeCreation = dateTimeCreation;
		this.dateTimeModified = dateTimeModified;
		this.changeoverId = changeoverId;
	}


	public ProductionMixingmilAutoGenerated() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	
}
