package web.minda.project.entity;

import java.util.LinkedHashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.*;

@Entity
@Table(name = "production_planning_changeover_plan")
public class ProductionPlanningChangeoverPlan {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	private Long changeoverId;

	@Column(name = "sequence_no")
	private Long sequenceNo;

	@Column(name = "article")
	private String article;

	@Column(name = "batch_code")
	private String batchCode;

	@Column(name = "mould_name")
	private String mouldName;

	@Column(name = "duplicate_mould_name")
	private String duplicateMouldName;

	@Column(name = "child_part_name")
	private String childPartName;

	@Column(name = "child_part_type")
	private String childPartType;

	@Column(name = "planned_shots")
	private Long plannedShots;

	@Column(name = "priority")
	private String priority;

	@Column(name = "planned_date")
	private String plannedDate;

	@Column(name = "created_by")
	private String createdBy;

	@Column(name = "status")
	private String status;

	@Column(name = "date_time_creation")
	private String dateTimeCreation;

	@Column(name = "date_time_modified")
	private String dateTimeModified;

	@Column(name = "machine_name")
	private String machineName;

	@Column(name = "tonnage")
	private String tonnage;

	@Column(name = "remark")
	private String remark;

	@Column(name = "image")
	private String image;

	@Column(name = "pending_shots")
	private Long pendingShots;
	
	
	@Column(name = "plan_type")
	private String planType;
	
	@Column(name = "auto_generated_saved")
	private Integer autoGeneratedSaved;
	
	@Column(name = "plan_id")
	private String planId;

	public Long getChangeoverId() {
		return changeoverId;
	}

	public void setChangeoverId(Long changeoverId) {
		this.changeoverId = changeoverId;
	}

	public Long getSequenceNo() {
		return sequenceNo;
	}

	public void setSequenceNo(Long sequenceNo) {
		this.sequenceNo = sequenceNo;
	}

	public String getArticle() {
		return article;
	}

	public void setArticle(String article) {
		this.article = article;
	}

	public String getBatchCode() {
		return batchCode;
	}

	public void setBatchCode(String batchCode) {
		this.batchCode = batchCode;
	}

	public String getMouldName() {
		return mouldName;
	}

	public void setMouldName(String mouldName) {
		this.mouldName = mouldName;
	}

	public String getDuplicateMouldName() {
		return duplicateMouldName;
	}

	public void setDuplicateMouldName(String duplicateMouldName) {
		this.duplicateMouldName = duplicateMouldName;
	}

	public String getChildPartName() {
		return childPartName;
	}

	public void setChildPartName(String childPartName) {
		this.childPartName = childPartName;
	}

	public String getChildPartType() {
		return childPartType;
	}

	public void setChildPartType(String childPartType) {
		this.childPartType = childPartType;
	}

	public Long getPlannedShots() {
		return plannedShots;
	}

	public void setPlannedShots(Long plannedShots) {
		this.plannedShots = plannedShots;
	}

	public String getPriority() {
		return priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	public String getPlannedDate() {
		return plannedDate;
	}

	public void setPlannedDate(String plannedDate) {
		this.plannedDate = plannedDate;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDateTimeCreation() {
		return dateTimeCreation;
	}

	public void setDateTimeCreation(String dateTimeCreation) {
		this.dateTimeCreation = dateTimeCreation;
	}

	public String getDateTimeModified() {
		return dateTimeModified;
	}

	public void setDateTimeModified(String dateTimeModified) {
		this.dateTimeModified = dateTimeModified;
	}

	public String getMachineName() {
		return machineName;
	}

	public void setMachineName(String machineName) {
		this.machineName = machineName;
	}

	public String getTonnage() {
		return tonnage;
	}

	public void setTonnage(String tonnage) {
		this.tonnage = tonnage;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Long getPendingShots() {
		return pendingShots;
	}

	public void setPendingShots(Long pendingShots) {
		this.pendingShots = pendingShots;
	}

	public String getPlanType() {
		return planType;
	}

	public void setPlanType(String planType) {
		this.planType = planType;
	}

	public Integer getAutoGeneratedSaved() {
		return autoGeneratedSaved;
	}

	public void setAutoGeneratedSaved(Integer autoGeneratedSaved) {
		this.autoGeneratedSaved = autoGeneratedSaved;
	}

	public String getPlanId() {
		return planId;
	}

	public void setPlanId(String planId) {
		this.planId = planId;
	}

	@Override
	public String toString() {
		return "ProductionPlanningChangeoverPlan [changeoverId=" + changeoverId + ", sequenceNo=" + sequenceNo
				+ ", article=" + article + ", batchCode=" + batchCode + ", mouldName=" + mouldName
				+ ", duplicateMouldName=" + duplicateMouldName + ", childPartName=" + childPartName + ", childPartType="
				+ childPartType + ", plannedShots=" + plannedShots + ", priority=" + priority + ", plannedDate="
				+ plannedDate + ", createdBy=" + createdBy + ", status=" + status + ", dateTimeCreation="
				+ dateTimeCreation + ", dateTimeModified=" + dateTimeModified + ", machineName=" + machineName
				+ ", tonnage=" + tonnage + ", remark=" + remark + ", image=" + image + ", pendingShots=" + pendingShots
				+ ", planType=" + planType + ", autoGeneratedSaved=" + autoGeneratedSaved + ", planId=" + planId + "]";
	}

	public ProductionPlanningChangeoverPlan(Long changeoverId, Long sequenceNo, String article, String batchCode,
			String mouldName, String duplicateMouldName, String childPartName, String childPartType, Long plannedShots,
			String priority, String plannedDate, String createdBy, String status, String dateTimeCreation,
			String dateTimeModified, String machineName, String tonnage, String remark, String image, Long pendingShots,
			String planType, Integer autoGeneratedSaved, String planId) {
		super();
		this.changeoverId = changeoverId;
		this.sequenceNo = sequenceNo;
		this.article = article;
		this.batchCode = batchCode;
		this.mouldName = mouldName;
		this.duplicateMouldName = duplicateMouldName;
		this.childPartName = childPartName;
		this.childPartType = childPartType;
		this.plannedShots = plannedShots;
		this.priority = priority;
		this.plannedDate = plannedDate;
		this.createdBy = createdBy;
		this.status = status;
		this.dateTimeCreation = dateTimeCreation;
		this.dateTimeModified = dateTimeModified;
		this.machineName = machineName;
		this.tonnage = tonnage;
		this.remark = remark;
		this.image = image;
		this.pendingShots = pendingShots;
		this.planType = planType;
		this.autoGeneratedSaved = autoGeneratedSaved;
		this.planId = planId;
	}

	public ProductionPlanningChangeoverPlan() {
		super();
		// TODO Auto-generated constructor stub
	}

	
	


}